name: pyinstaller
on: workflow_dispatch
jobs:
  build-on-windows:
    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install pyinstaller
        run: pip install pyinstaller
      - name: build exe
        run: pyinstaller sha256.py -F
      - name: upload exe file
        uses: actions/upload-artifact@v4
        with:
          name: sha256-windows-exe
          path: dist/sha256.exe

  test-build-artifacts:
    runs-on: windows-latest
    steps:
      - name: download exe file
        uses: actions/download-artifact@v4
        with:
          name: sha256-windows-exe
      - name: test exe file
        run: |
          ls
          ./sha256.exe sha256.exe
