name: workflow_secrets
on:
  workflow_dispatch:
jobs:
  test-screts:
    environment: test
    env:
      DB_U: ${{ vars.DB_USER }}
      DB_P: ${{ secrets.DB_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: check env U
        run: echo "u=${{ env.DB_U }}"
      - name: check env P
        run: echo "p=${{ env.DB_P }}"
  prod-screts:
    environment: prod
    env:
      DB_U: ${{ vars.DB_USER }}
      DB_P: ${{ secrets.DB_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: check env U
        run: echo "u=${{ env.DB_U }}"
      - name: check env P
        run: echo "p=${{ env.DB_P }}"

