name: workflow_secrets
on:
  workflow_dispatch:
env:
  DB_U: ${{ secrets:DB_USER }}
  DB_P: ${{ secrets:DB_PASSWORD }}
jobs:
  test-screts:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: check env U
        run: echo "u=${{ env.DB_U }}"
      - name: check env P
        run: echo "p=${{ env.DB_P }}"
